version: "3.9"
services:
  noticebee-cedp-api:
    build: server/.
    ports:
      - "1338:5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  noticebee-cedp-client:
    build: client/.
    ports:
      - "5000"
    environment:
      - VITE_API_URL=noticebee-cedp-api
    depends_on:
      - noticebee-cedp-api
  redis:
    image: "redis:alpine"
  # s3cmd:
  #   image: "garland/docker-s3cmd"
  #   environment:
  #     - aws_key=QI6NZMF168674QVS1GIT
  #     - aws_secret=XHv3hFZKfQANCTv83qSzsjDLP698hwR1VbVWIfFV
  #     - cmd=interactive
  #     - SRC_S3=%(bucket)s.ap-south-1.linodeobjects.com
